# Generated by Django 3.2.4 on 2021-06-14 01:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='blocks',
            field=models.ManyToManyField(related_name='block', to=settings.AUTH_USER_MODEL),
        ),
    ]
