# Generated by Django 3.2.4 on 2021-06-14 15:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0002_post_blocks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='blocks',
            field=models.ManyToManyField(blank=True, related_name='block', to=settings.AUTH_USER_MODEL),
        ),
    ]
